from numpy import broadcast
from pages.mobile_test import Mobile_Test
from appium import webdriver
from appium.webdriver.common.touch_action import TouchAction
def test_Mobile(browser):

    # Mobile_Test(browser).get_Remote_driver_Status()
    # Mobile_Test(browser).Execute_Mobile_Command()
    # Mobile_Test(browser).create_newSession()
    # Mobile_Test(browser).End_Session()
    # Mobile_Test(browser).Get_Session_Capabilities()
    # Mobile_Test(browser).Set_Orientation()   Message: Screen rotation cannot be changed to ROTATION_270
    # Mobile_Test(browser).getlogs()
    # Mobile_Test(browser).Update_settingS()
    # Mobile_Test(browser).execute_driver()
    # Mobile_Test(browser).Removeapp()
    # Mobile_Test(browser).push_file_To_Device_From_location()
    # Mobile_Test(browser).pull_file_from_device()
    # Mobile_Test(browser).pull_folder_from_device()
    # Mobile_Test(browser).shake_Device()                              essage: Method has not yet been implemented
    # Mobile_Test(browser).get_performance_data()           get_performance_Data() missing 1 required positional argument: 'data_type'
    # Mobile_Test(browser).Get_system_Bars()               An unknown server-side error occurred while processing
    # Mobile_Test(browser).Clear_element()
    # Mobile_Test(browser).submit_form_element()
    # Mobile_Test(browser).get_value_of_Css_property()
    # Mobile_Test(browser).finger_Touch_scroll()
    # Mobile_Test(browser).finger_Touch_flick()    TypeError: ActionHelpers() takes no arguments

    # Mobile_Test(browser).Move_the_mouse_toEleement_click_and_Hold()
    # Mobile_Test(browser).Move_the_mouse_toEleement_double_Click()
    # Mobile_Test(browser).Move_the_mouse_toEleement_Release()
    # Mobile_Test(browser).Move_the_Mouse_by_an_offset()
    # Mobile_Test(browser).Move_the_mouse_toeleement_SubElement_click()
    # Mobile_Test(browser).get_active_Element()

    Mobile_Test(browser).Click_element()
    Mobile_Test(browser).go_back()
    Mobile_Test(browser).Take_screenshot()
    Mobile_Test(browser).Get_pageSource()
    Mobile_Test(browser).Get_Orientation()
    Mobile_Test(browser).getLog_types()
    Mobile_Test(browser).sendApp_To_background()
    Mobile_Test(browser).reset_app()
    Mobile_Test(browser).close_app()
    Mobile_Test(browser).Launch_app()
    # Mobile_Test(browser).get_GeoLocation()
    Mobile_Test(browser).close_app()
    Mobile_Test(browser).Get_Orientation()  
    Mobile_Test(browser).Log_event()
    Mobile_Test(browser).Get_event()
    Mobile_Test(browser).Get_Settings()
    Mobile_Test(browser).install_App()
    Mobile_Test(browser).isApp_Installed()
    Mobile_Test(browser).Terminate_app()
    Mobile_Test(browser).activate_app()
    Mobile_Test(browser).Get_Clipboard()
    Mobile_Test(browser).Get_ClipboardTest()
    Mobile_Test(browser).Set_ClipBoard()
    Mobile_Test(browser).Set_Clipboard_Text()
    Mobile_Test(browser).Set_Power_Ac_forEmulator()
    Mobile_Test(browser).set_Power_capacity_forEmulator()
    Mobile_Test(browser).Lock_device()
    Mobile_Test(browser).Unlock_device()
    Mobile_Test(browser).isDevice_LockeD()
    Mobile_Test(browser).Launch_app()
    Mobile_Test(browser).Click_element()
    Mobile_Test(browser).press_Key_Code()
    Mobile_Test(browser).Logng_press_Key_code()
    Mobile_Test(browser).Is_Keyboard_Shown()
    Mobile_Test(browser).key_event()
    Mobile_Test(browser).Hide_Key_board()
    Mobile_Test(browser).toggle_Wifi_service()
    Mobile_Test(browser).toggle_locatioN_services()
    Mobile_Test(browser).send_SmsEemulatorOnly()
    Mobile_Test(browser).make_GSM_call_EmulatorOnlY()
    Mobile_Test(browser).set_GSM_Signal_strength_emulatorOnly()
    Mobile_Test(browser).Set_GSM_signal_emulatorOnly()
    Mobile_Test(browser).set_Network_speed_emulatorOnly()
    Mobile_Test(browser).start_Recording_Screen()
    Mobile_Test(browser).stop_Recording_Screen()
    Mobile_Test(browser).open_Notifications_andriod_emulatorOnly()
    Mobile_Test(browser).get_Device_Time()
    Mobile_Test(browser).get_Display_density_android()
    Mobile_Test(browser).Finger_print_android_emulator()
    Mobile_Test(browser).get_performance_Data_Types()
    Mobile_Test(browser).Click_element()
    Mobile_Test(browser).entertext()
    Mobile_Test(browser).GetText()
    Mobile_Test(browser).get_TagName()
    Mobile_Test(browser).Get_Attribute()
    Mobile_Test(browser).is_enabled()
    Mobile_Test(browser).is_displayed()
    Mobile_Test(browser).is_selected()
    Mobile_Test(browser).get_Location()
    Mobile_Test(browser).get_Element_Size_inPixel()
    Mobile_Test(browser).get_Element_dimensions_Coordinates()
    Mobile_Test(browser).get_location_in_View()
    Mobile_Test(browser).single_Tap_element()
    Mobile_Test(browser).double_Tap_element() 
    Mobile_Test(browser).Move_the_mouse_toEleement_click()
    Mobile_Test(browser).finger_Press_and_move()
    Mobile_Test(browser).Finger_press_move_Release()
    Mobile_Test(browser).finger_Long_Press()
    Mobile_Test(browser).finger_Multi_TouchAction()
